# Dart/Flutter static analysis and linting
# https://dart.dev/tools/analysis
# Run: flutter analyze

include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "build/**"
    - "**/generated/**"
  errors:
    missing_return: error
    invalid_assignment: error

linter:
  rules:
    prefer_single_quotes: true
    sort_child_properties_last: true
    use_super_parameters: true
    avoid_print: true
    avoid_empty_else: true
    cancel_subscriptions: true
    close_sinks: true
    literal_only_boolean_expressions: true
    no_duplicate_case_values: true
    throw_in_finally: true
    unnecessary_statements: true
    unrelated_type_equality_checks: true
    valid_regexps: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_fields: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    deprecated_consistency: true
    empty_catches: true
    empty_constructor_bodies: true
    prefer_contains: true
    prefer_if_null_operators: true
    prefer_null_aware_operators: true
    prefer_spread_collections: true
    slash_for_doc_comments: true
    unawaited_futures: true
    unnecessary_await_in_return: true
    unnecessary_brace_in_string_interps: true
    unnecessary_const: true
    unnecessary_lambdas: true
    unnecessary_null_checks: true
    unnecessary_parenthesis: true
    unnecessary_string_interpolations: true
    unnecessary_this: true
    use_build_context_synchronously: true
    use_colored_box: true
    use_decorated_box: true
    use_key_in_widget_constructors: true
    use_rethrow_when_possible: true
