// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

import '../Api/api_key.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get android => FirebaseOptions(
    apiKey: firebaseOptionsKey,
    appId: firebaseAppId,
    messagingSenderId: '412268788730',
    projectId: 'juxeboxd',
    storageBucket: 'juxeboxd.appspot.com',
  );

  static FirebaseOptions get ios => FirebaseOptions(
    apiKey: firebaseOptionsKey,
    appId: firebaseAppId,
    messagingSenderId: '412268788730',
    projectId: 'juxeboxd',
    storageBucket: 'juxeboxd.appspot.com',
    iosClientId:
        '412268788730-scupqhk1ra16uvnb6cp1tm3uar8lhv3s.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTestProject',
  );

  static FirebaseOptions get web => FirebaseOptions(
    apiKey: firebaseOptionsKey,
    appId: firebaseAppId.isNotEmpty ? firebaseAppId : '1:412268788730:web:ba888c5cdf66b317fe8243',
    messagingSenderId: '412268788730',
    projectId: 'juxeboxd',
    authDomain: 'juxeboxd.firebaseapp.com',
    storageBucket: 'juxeboxd.appspot.com',
  );
}
